/*
: MIT license
 Lettering.JS 0.7.0

 Copyright 2010, Dave Rupert http://daverupert.com
 Released under the WTFPL license
 http://sam.zoy.org/wtfpl/

 Thanks to Paul Irish - http://paulirish.com - for the feedback.

 Date: Mon Sep 20 17:14:00 2010 -0600
 Particleground

 @author Jonathan Nicol - @mrjnicol
 @version 1.1.0
 @description Creates a canvas based particle system background

 Inspired by http://requestlab.fr/ and http://disruptivebydesign.com/
*/
!function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b("object"==typeof module&&module.exports?require("jquery"):jQuery)}(function(b){function m(a){var c={},d=/^jQuery\d+$/;return b.each(a.attributes,function(a,b){b.specified&&!d.test(b.name)&&(c[b.name]=b.value)}),c}function h(a,c){var d=b(this);if(this.value==d.attr("placeholder")&&d.hasClass(n.customClass))if(d.data("placeholder-password")){if(d=d.hide().nextAll('input[type="password"]:first').show().attr("id",d.removeAttr("id").data("placeholder-id")),
!0===a)return d[0].value=c;d.focus()}else this.value="",d.removeClass(n.customClass),this==g()&&this.select()}function k(){var a,c=b(this),d=this.id;if(""===this.value){if("password"===this.type){if(!c.data("placeholder-textinput")){try{a=c.clone().prop({type:"text"})}catch(q){a=b("<input>").attr(b.extend(m(this),{type:"text"}))}a.removeAttr("name").data({"placeholder-password":c,"placeholder-id":d}).bind("focus.placeholder",h);c.data({"placeholder-textinput":a,"placeholder-id":d}).before(a)}c=c.removeAttr("id").hide().prevAll('input[type="text"]:first').attr("id",
d).show()}c.addClass(n.customClass);c[0].value=c.attr("placeholder")}else c.removeClass(n.customClass)}function g(){try{return document.activeElement}catch(r){}}var e,f="[object OperaMini]"==Object.prototype.toString.call(window.operamini),a="placeholder"in document.createElement("input")&&!f,f="placeholder"in document.createElement("textarea")&&!f,x=b.valHooks,p=b.propHooks;if(a&&f)e=b.fn.placeholder=function(){return this},e.input=e.textarea=!0;else{var n={};e=b.fn.placeholder=function(f){n=b.extend({},
{customClass:"placeholder"},f);return this.filter((a?"textarea":":input")+"[placeholder]").not("."+n.customClass).bind({"focus.placeholder":h,"blur.placeholder":k}).data("placeholder-enabled",!0).trigger("blur.placeholder"),this};e.input=a;e.textarea=f;e={get:function(a){var c=b(a),d=c.data("placeholder-password");return d?d[0].value:c.data("placeholder-enabled")&&c.hasClass(n.customClass)?"":a.value},set:function(a,c){var d=b(a),f=d.data("placeholder-password");return f?f[0].value=c:d.data("placeholder-enabled")?
(""===c?(a.value=c,a!=g()&&k.call(a)):d.hasClass(n.customClass)?h.call(a,!0,c)||(a.value=c):a.value=c,d):a.value=c}};a||(x.input=e,p.value=e);f||(x.textarea=e,p.value=e);b(function(){b(document).delegate("form","submit.placeholder",function(){var a=b("."+n.customClass,this).each(h);setTimeout(function(){a.each(k)},10)})});b(window).bind("beforeunload.placeholder",function(){b("."+n.customClass).each(function(){this.value=""})})}});
(function(b){function m(k,g,e,f){var a=k.text();g=a.split(g);var h="";g.length&&(b(g).each(function(a,b){h+='<span class="'+e+(a+1)+'" aria-hidden="true">'+b+"</span>"+f}),k.attr("aria-label",a).empty().append(h))}var h={init:function(){return this.each(function(){m(b(this),"","char","")})},words:function(){return this.each(function(){m(b(this)," ","word"," ")})},lines:function(){return this.each(function(){m(b(this).children("br").replaceWith("eefec303079ad17405c889e092e105b0").end(),"eefec303079ad17405c889e092e105b0",
"line","")})}};b.fn.lettering=function(k){if(k&&h[k])return h[k].apply(this,[].slice.call(arguments,1));if("letters"===k||!k)return h.init.apply(this,[].slice.call(arguments,0));b.error("Method "+k+" does not exist on jQuery.lettering");return this}})(jQuery);
(function(b){b.fn.fitText=function(m,h){var k=m||1,g=b.extend({minFontSize:Number.NEGATIVE_INFINITY,maxFontSize:Number.POSITIVE_INFINITY},h);return this.each(function(){var e=b(this),f=function(){e.css("font-size",Math.max(Math.min(e.width()/(10*k),parseFloat(g.maxFontSize)),parseFloat(g.minFontSize)))};f();b(window).on("resize.fittext orientationchange.fittext",f)})}})(jQuery);
!function(b,m){function h(b){b=b||{};for(var a=1;a<arguments.length;a++){var f=arguments[a];if(f)for(var e in f)f.hasOwnProperty(e)&&("object"==typeof f[e]?deepExtend(b[e],f[e]):b[e]=f[e])}return b}function k(f,a){function k(){c.width=f.offsetWidth;c.height=f.offsetHeight;d.fillStyle=a.dotColor;d.strokeStyle=a.lineColor;d.lineWidth=a.lineWidth}function p(){if(y){q=b.innerWidth;t=b.innerHeight;d.clearRect(0,0,c.width,c.height);for(var a=0;a<l.length;a++)l[a].updatePosition();for(a=0;a<l.length;a++)l[a].draw();
u||requestAnimationFrame(p)}}function n(){switch(this.stackPos,this.active=!0,this.layer=Math.ceil(3*Math.random()),this.parallaxOffsetX=0,this.parallaxOffsetY=0,this.position={x:Math.ceil(Math.random()*c.width),y:Math.ceil(Math.random()*c.height)},this.speed={},a.directionX){case "left":this.speed.x=+(-a.maxSpeedX+Math.random()*a.maxSpeedX-a.minSpeedX).toFixed(2);break;case "right":this.speed.x=+(Math.random()*a.maxSpeedX+a.minSpeedX).toFixed(2);break;default:this.speed.x=+(-a.maxSpeedX/2+Math.random()*
a.maxSpeedX).toFixed(2),this.speed.x+=0<this.speed.x?a.minSpeedX:-a.minSpeedX}switch(a.directionY){case "up":this.speed.y=+(-a.maxSpeedY+Math.random()*a.maxSpeedY-a.minSpeedY).toFixed(2);break;case "down":this.speed.y=+(Math.random()*a.maxSpeedY+a.minSpeedY).toFixed(2);break;default:this.speed.y=+(-a.maxSpeedY/2+Math.random()*a.maxSpeedY).toFixed(2),this.speed.x+=0<this.speed.y?a.minSpeedY:-a.minSpeedY}}function r(b){void 0!==a[b]&&a[b].call(f)}var c,d,q,t,v,w,y=!!m.createElement("canvas").getContext,
l=[],z=0,A=0,B=!navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry|BB10|mobi|tablet|opera mini|nexus 7)/i),C=!!b.DeviceOrientationEvent,D=0,E=0,u=!1;return a=h({},b[g].defaults,a),n.prototype.draw=function(){d.beginPath();d.arc(this.position.x+this.parallaxOffsetX,this.position.y+this.parallaxOffsetY,a.particleRadius/2,0,2*Math.PI,!0);d.closePath();d.fill();d.beginPath();for(var b=l.length-1;b>this.stackPos;b--){var c=l[b],f=this.position.x-c.position.x,e=this.position.y-c.position.y;
Math.sqrt(f*f+e*e).toFixed(2)<a.proximity&&(d.moveTo(this.position.x+this.parallaxOffsetX,this.position.y+this.parallaxOffsetY),a.curvedLines?d.quadraticCurveTo(Math.max(c.position.x,c.position.x),Math.min(c.position.y,c.position.y),c.position.x+c.parallaxOffsetX,c.position.y+c.parallaxOffsetY):d.lineTo(c.position.x+c.parallaxOffsetX,c.position.y+c.parallaxOffsetY))}d.stroke();d.closePath()},n.prototype.updatePosition=function(){a.parallax&&(C&&!B?(v=(q-0)/60*(D- -30)+0,w=(t-0)/60*(E- -30)+0):(v=
z,w=A),this.parallaxTargX=(v-q/2)/(a.parallaxMultiplier*this.layer),this.parallaxOffsetX+=(this.parallaxTargX-this.parallaxOffsetX)/10,this.parallaxTargY=(w-t/2)/(a.parallaxMultiplier*this.layer),this.parallaxOffsetY+=(this.parallaxTargY-this.parallaxOffsetY)/10);var b=f.offsetWidth,c=f.offsetHeight;switch(a.directionX){case "left":0>this.position.x+this.speed.x+this.parallaxOffsetX&&(this.position.x=b-this.parallaxOffsetX);break;case "right":this.position.x+this.speed.x+this.parallaxOffsetX>b&&(this.position.x=
0-this.parallaxOffsetX);break;default:(this.position.x+this.speed.x+this.parallaxOffsetX>b||0>this.position.x+this.speed.x+this.parallaxOffsetX)&&(this.speed.x=-this.speed.x)}switch(a.directionY){case "up":0>this.position.y+this.speed.y+this.parallaxOffsetY&&(this.position.y=c-this.parallaxOffsetY);break;case "down":this.position.y+this.speed.y+this.parallaxOffsetY>c&&(this.position.y=0-this.parallaxOffsetY);break;default:(this.position.y+this.speed.y+this.parallaxOffsetY>c||0>this.position.y+this.speed.y+
this.parallaxOffsetY)&&(this.speed.y=-this.speed.y)}this.position.x+=this.speed.x;this.position.y+=this.speed.y},n.prototype.setStackPos=function(a){this.stackPos=a},function(){if(y){c=m.createElement("canvas");c.className="pg-canvas";c.style.display="block";f.insertBefore(c,f.firstChild);d=c.getContext("2d");k();for(var e=Math.round(c.width*c.height/a.density),g=0;e>g;g++){var h=new n;h.setStackPos(g);l.push(h)}b.addEventListener("resize",function(){k();for(var b=f.offsetWidth,e=f.offsetHeight,d=
l.length-1;0<=d;d--)(l[d].position.x>b||l[d].position.y>e)&&l.splice(d,1);b=Math.round(c.width*c.height/a.density);if(b>l.length)for(;b>l.length;)e=new n,l.push(e);else b<l.length&&l.splice(b);for(d=l.length-1;0<=d;d--)l[d].setStackPos(d)},!1);m.addEventListener("mousemove",function(a){z=a.pageX;A=a.pageY},!1);C&&!B&&b.addEventListener("deviceorientation",function(){E=Math.min(Math.max(-event.beta,-30),30);D=Math.min(Math.max(-event.gamma,-30),30)},!0);p();r("onInit")}}(),{option:function(b,c){return c?
void(a[b]=c):a[b]},destroy:function(){console.log("destroy");c.parentNode.removeChild(c);r("onDestroy");e&&e(f).removeData("plugin_"+g)},start:function(){u=!1;p()},pause:function(){u=!0}}}var g="particleground",e=b.jQuery;b[g]=function(b,a){return new k(b,a)};b[g].defaults={minSpeedX:.1,maxSpeedX:.7,minSpeedY:.1,maxSpeedY:.7,directionX:"center",directionY:"center",density:1E4,dotColor:"#666666",lineColor:"#666666",particleRadius:7,lineWidth:1,curvedLines:!1,proximity:100,parallax:!0,parallaxMultiplier:5,
onInit:function(){},onDestroy:function(){}};e&&(e.fn[g]=function(b){if("string"==typeof arguments[0]){var a,f=arguments[0],h=Array.prototype.slice.call(arguments,1);return this.each(function(){e.data(this,"plugin_"+g)&&"function"==typeof e.data(this,"plugin_"+g)[f]&&(a=e.data(this,"plugin_"+g)[f].apply(this,h))}),void 0!==a?a:this}return"object"!=typeof b&&b?void 0:this.each(function(){e.data(this,"plugin_"+g)||e.data(this,"plugin_"+g,new k(this,b))})})}(window,document);
(function(){for(var b=0,m=["ms","moz","webkit","o"],h=0;h<m.length&&!window.requestAnimationFrame;++h)window.requestAnimationFrame=window[m[h]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[m[h]+"CancelAnimationFrame"]||window[m[h]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(h){var g=(new Date).getTime(),e=Math.max(0,16-(g-b)),f=window.setTimeout(function(){h(g+e)},e);return b=g+e,f});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(b){clearTimeout(b)})})();